<?php

namespace Database\Seeders;

use App\Models\Conversation;
use App\Models\LearningCategory;
use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class EnglishLearningSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categoriesData = [
            [
                'slug' => 'abjad-fonetik-dasar',
                'name' => 'Abjad, Fonetik & Suara Dasar',
                'level' => 'beginner',
                'icon' => '🔤',
                'color_theme' => 'blue',
                'description' => 'Kuasai dasar pelafalan huruf vokal, konsonan penting (th, sh, ch), dan ejaan bahasa Inggris.',
                'sort_order' => 1,
                'vocabularies' => [
                    [
                        'word' => 'Alphabet',
                        'phonetic' => '/ˈæl.fə.bet/',
                        'part_of_speech' => 'Noun',
                        'translation' => 'Abjad / Alfabet',
                        'example_sentence' => 'English has twenty-six letters in its alphabet.',
                        'example_translation' => 'Bahasa Inggris memiliki 26 huruf dalam alfabetnya.',
                        'pronunciation_tip' => 'Tekan suku kata pertama: AL-fə-bet.',
                        'difficulty' => 'basic',
                    ],
                    [
                        'word' => 'Vowel',
                        'phonetic' => '/ˈvaʊ.əl/',
                        'part_of_speech' => 'Noun',
                        'translation' => 'Huruf Vokal (A, E, I, O, U)',
                        'example_sentence' => 'Every English word contains at least one vowel sound.',
                        'example_translation' => 'Setiap kata bahasa Inggris memiliki setidaknya satu bunyi vokal.',
                        'pronunciation_tip' => 'Berdengung lembut: \'Vau-el\'.',
                        'difficulty' => 'basic',
                    ],
                    [
                        'word' => 'Consonant',
                        'phonetic' => '/ˈkɒn.sə.nənt/',
                        'part_of_speech' => 'Noun',
                        'translation' => 'Huruf Konsonan / Mati',
                        'example_sentence' => 'The letters B, C, and D are consonants.',
                        'example_translation' => 'Huruf B, C, dan D adalah huruf konsonan.',
                        'pronunciation_tip' => 'Ucapkan \'KON-so-nant\'.',
                        'difficulty' => 'basic',
                    ],
                    [
                        'word' => 'Pronounce',
                        'phonetic' => '/prəˈnaʊns/',
                        'part_of_speech' => 'Verb',
                        'translation' => 'Mengucapkan / Melafalkan',
                        'example_sentence' => 'How do you pronounce your last name?',
                        'example_translation' => 'Bagaimana kamu mengucapkan nama belakangmu?',
                        'pronunciation_tip' => 'Ingat berbunyi \'pra-NAUNS\', bukan pro-nounce.',
                        'difficulty' => 'basic',
                    ],
                    [
                        'word' => 'Sound',
                        'phonetic' => '/saʊnd/',
                        'part_of_speech' => 'Noun',
                        'translation' => 'Bunyi / Suara',
                        'example_sentence' => 'The "th" sound is tricky for beginners.',
                        'example_translation' => 'Bunyi "th" cukup menantang bagi pemula.',
                        'pronunciation_tip' => 'Ujung lidah dijepit sedikit di antara gigi depan.',
                        'difficulty' => 'basic',
                    ],
                    [
                        'word' => 'Listen',
                        'phonetic' => '/ˈlɪs.ən/',
                        'part_of_speech' => 'Verb',
                        'translation' => 'Mendengarkan',
                        'example_sentence' => 'Please listen carefully to the native speaker.',
                        'example_translation' => 'Tolong dengarkan dengan seksama penutur asli.',
                        'pronunciation_tip' => 'Huruf \'t\' di tengah tidak dibaca (silent t): \'LIS-en\'.',
                        'difficulty' => 'basic',
                    ],
                    [
                        'word' => 'Repeat',
                        'phonetic' => '/rɪˈpiːt/',
                        'part_of_speech' => 'Verb',
                        'translation' => 'Mengulang / Menirukan',
                        'example_sentence' => 'Repeat the phrase after the audio plays.',
                        'example_translation' => 'Ulangi frasa tersebut setelah audio berbunyi.',
                        'pronunciation_tip' => 'Bunyi \'ee\' panjang: \'ri-PEEET\'.',
                        'difficulty' => 'basic',
                    ],
                ],
            ],
            [
                'slug' => 'salam-perkenalan',
                'name' => 'Salam & Perkenalan Diri',
                'level' => 'beginner',
                'icon' => '👋',
                'color_theme' => 'violet',
                'description' => 'Kalimat sapaan harian, cara memperkenalkan nama, asal, pekerjaan, dan basa-basi sopan.',
                'sort_order' => 2,
                'vocabularies' => [
                    [
                        'word' => 'Hello',
                        'phonetic' => '/həˈloʊ/',
                        'part_of_speech' => 'Interjection',
                        'translation' => 'Halo / Hai',
                        'example_sentence' => 'Hello! It is wonderful to meet you today.',
                        'example_translation' => 'Halo! Senang sekali bisa bertemu denganmu hari ini.',
                        'pronunciation_tip' => 'Tenggorokan santai: \'he-LOU\'.',
                        'difficulty' => 'basic',
                    ],
                    [
                        'word' => 'Good morning',
                        'phonetic' => '/ɡʊd ˈmɔːr.nɪŋ/',
                        'part_of_speech' => 'Phrase',
                        'translation' => 'Selamat pagi',
                        'example_sentence' => 'Good morning, everyone! Let us begin our lesson.',
                        'example_translation' => 'Selamat pagi semuanya! Mari kita mulai pelajaran kita.',
                        'pronunciation_tip' => 'Gud MOR-ning (hindari menekan \'g\' di akhir terlalu keras).',
                        'difficulty' => 'basic',
                    ],
                    [
                        'word' => 'Pleased to meet you',
                        'phonetic' => '/pliːzd tuː miːt juː/',
                        'part_of_speech' => 'Phrase',
                        'translation' => 'Senang berkenalan dengan Anda (sopan)',
                        'example_sentence' => 'My name is Sarah. Pleased to meet you!',
                        'example_translation' => 'Nama saya Sarah. Senang sekali berkenalan dengan Anda!',
                        'pronunciation_tip' => 'Sambungkan suara \'pleased to\' -> \'pliiz-tu\'.',
                        'difficulty' => 'basic',
                    ],
                    [
                        'word' => 'How are you doing?',
                        'phonetic' => '/haʊ ɑːr juː ˈduː.ɪŋ/',
                        'part_of_speech' => 'Phrase',
                        'translation' => 'Bagaimana kabarmu? (sapaan santai)',
                        'example_sentence' => 'Hey Alex, how are you doing these days?',
                        'example_translation' => 'Hai Alex, bagaimana kabarmu akhir-akhir ini?',
                        'pronunciation_tip' => 'Alami dan cepat: \'hau-ya-duing?\'.',
                        'difficulty' => 'basic',
                    ],
                    [
                        'word' => 'Introduce',
                        'phonetic' => '/ˌɪn.trəˈdjuːs/',
                        'part_of_speech' => 'Verb',
                        'translation' => 'Memperkenalkan',
                        'example_sentence' => 'Allow me to introduce my colleague, David.',
                        'example_translation' => 'Izinkan saya memperkenalkan rekan saya, David.',
                        'pronunciation_tip' => 'In-tro-DYOOS, penekanan di akhir.',
                        'difficulty' => 'basic',
                    ],
                    [
                        'word' => 'Where are you from?',
                        'phonetic' => '/weər ɑːr juː frɒm/',
                        'part_of_speech' => 'Phrase',
                        'translation' => 'Dari mana asalmu?',
                        'example_sentence' => 'Where are you from? I am from Jakarta, Indonesia.',
                        'example_translation' => 'Dari mana asalmu? Saya berasal dari Jakarta, Indonesia.',
                        'pronunciation_tip' => 'Intonasi menurun di akhir kalimat tanya w-h.',
                        'difficulty' => 'basic',
                    ],
                    [
                        'word' => 'Farewell',
                        'phonetic' => '/ˌfeərˈwel/',
                        'part_of_speech' => 'Noun / Interjection',
                        'translation' => 'Perpisahan / Selamat tinggal',
                        'example_sentence' => 'They waved farewell as the train left the platform.',
                        'example_translation' => 'Mereka melambaikan selamat tinggal saat kereta meninggalkan peron.',
                        'pronunciation_tip' => 'Fair-WEL.',
                        'difficulty' => 'daily',
                    ],
                ],
            ],
            [
                'slug' => 'angka-waktu-jadwal',
                'name' => 'Angka, Jam & Waktu',
                'level' => 'beginner',
                'icon' => '⏰',
                'color_theme' => 'emerald',
                'description' => 'Menghitung, membaca jam (quarter past/half past), hari, bulan, dan menyusun janji temu.',
                'sort_order' => 3,
                'vocabularies' => [
                    [
                        'word' => 'Quarter past',
                        'phonetic' => '/ˈkwɔːr.tər pæst/',
                        'part_of_speech' => 'Phrase',
                        'translation' => 'Lewat seperempat (15 menit)',
                        'example_sentence' => 'The bus will depart at a quarter past eight.',
                        'example_translation' => 'Bus akan berangkat pada pukul delapan lewat seperempat (08:15).',
                        'pronunciation_tip' => 'Kwor-ter past.',
                        'difficulty' => 'basic',
                    ],
                    [
                        'word' => 'Half past',
                        'phonetic' => '/hɑːf pæst/',
                        'part_of_speech' => 'Phrase',
                        'translation' => 'Lewat setengah jam (30 menit)',
                        'example_sentence' => 'Our flight is scheduled at half past two.',
                        'example_translation' => 'Penerbangan kita dijadwalkan pada pukul setengah tiga (02:30).',
                        'pronunciation_tip' => 'Huruf \'l\' pada \'half\' hening (silent l): \'Haaf past\'.',
                        'difficulty' => 'basic',
                    ],
                    [
                        'word' => 'Schedule',
                        'phonetic' => '/ˈskedʒ.uːl/',
                        'part_of_speech' => 'Noun / Verb',
                        'translation' => 'Jadwal / Menjadwalkan',
                        'example_sentence' => 'Let us check tomorrow\'s schedule.',
                        'example_translation' => 'Mari kita periksa jadwal untuk besok.',
                        'pronunciation_tip' => 'US: \'SKE-jul\', UK: \'SHE-dyool\'.',
                        'difficulty' => 'basic',
                    ],
                    [
                        'word' => 'Appointment',
                        'phonetic' => '/əˈpɔɪnt.mənt/',
                        'part_of_speech' => 'Noun',
                        'translation' => 'Janji temu',
                        'example_sentence' => 'I have a doctor\'s appointment this afternoon.',
                        'example_translation' => 'Saya punya janji temu dengan dokter siang ini.',
                        'pronunciation_tip' => 'ə-POINT-mənt.',
                        'difficulty' => 'daily',
                    ],
                    [
                        'word' => 'Punctual',
                        'phonetic' => '/ˈpʌŋk.tʃu.əl/',
                        'part_of_speech' => 'Adjective',
                        'translation' => 'Tepat waktu / Disiplin',
                        'example_sentence' => 'He is always punctual for business meetings.',
                        'example_translation' => 'Dia selalu tepat waktu dalam rapat bisnis.',
                        'pronunciation_tip' => 'PANGK-choo-əl.',
                        'difficulty' => 'daily',
                    ],
                ],
            ],
            [
                'slug' => 'makanan-restoran',
                'name' => 'Makanan, Minuman & Restoran',
                'level' => 'daily',
                'icon' => '🍽️',
                'color_theme' => 'rose',
                'description' => 'Kosakata kuliner, cara memesan meja, meminta rekomendasi, dan meminta tagihan bill.',
                'sort_order' => 4,
                'vocabularies' => [
                    [
                        'word' => 'Delicious',
                        'phonetic' => '/dɪˈlɪʃ.əs/',
                        'part_of_speech' => 'Adjective',
                        'translation' => 'Sangat lezat / Enak sekali',
                        'example_sentence' => 'This mushroom soup is absolutely delicious.',
                        'example_translation' => 'Sup jamur ini benar-benar sangat lezat.',
                        'pronunciation_tip' => 'Di-LI-syəs. Tekankan pada \'LI\'.',
                        'difficulty' => 'daily',
                    ],
                    [
                        'word' => 'Appetizer',
                        'phonetic' => '/ˈæp.ə.taɪ.zər/',
                        'part_of_speech' => 'Noun',
                        'translation' => 'Hidangan pembuka',
                        'example_sentence' => 'Would you like to order an appetizer first?',
                        'example_translation' => 'Apakah Anda ingin memesan hidangan pembuka terlebih dahulu?',
                        'pronunciation_tip' => 'A-pe-tai-zer.',
                        'difficulty' => 'daily',
                    ],
                    [
                        'word' => 'Main course',
                        'phonetic' => '/meɪn kɔːrs/',
                        'part_of_speech' => 'Noun',
                        'translation' => 'Hidangan utama',
                        'example_sentence' => 'For the main course, I will have the grilled salmon.',
                        'example_translation' => 'Untuk hidangan utama, saya pesan salmon panggang.',
                        'pronunciation_tip' => 'Mein kors.',
                        'difficulty' => 'daily',
                    ],
                    [
                        'word' => 'Could I get the check, please?',
                        'phonetic' => '/kʊd aɪ ɡet ðə tʃek pliːz/',
                        'part_of_speech' => 'Phrase',
                        'translation' => 'Bisa minta tagihan/bon-nya? (sopan)',
                        'example_sentence' => 'Excuse me, could we get the check, please?',
                        'example_translation' => 'Permisi, bisakah kami minta tagihannya?',
                        'pronunciation_tip' => 'Gunakan intonasi ramah naik di akhir kalimat sopan.',
                        'difficulty' => 'daily',
                    ],
                    [
                        'word' => 'Allergic',
                        'phonetic' => '/əˈlɜːr.dʒɪk/',
                        'part_of_speech' => 'Adjective',
                        'translation' => 'Alergi',
                        'example_sentence' => 'I am allergic to peanuts, does this dish contain nuts?',
                        'example_translation' => 'Saya alergi kacang, apakah masakan ini mengandung kacang?',
                        'pronunciation_tip' => 'ə-LER-jik.',
                        'difficulty' => 'daily',
                    ],
                    [
                        'word' => 'Beverage',
                        'phonetic' => '/ˈbev.ər.ɪdʒ/',
                        'part_of_speech' => 'Noun',
                        'translation' => 'Minuman (formal)',
                        'example_sentence' => 'What kinds of cold beverages do you serve?',
                        'example_translation' => 'Minuman dingin apa saja yang tersedia di sini?',
                        'pronunciation_tip' => 'BEV-rij.',
                        'difficulty' => 'daily',
                    ],
                ],
            ],
            [
                'slug' => 'belanja-dan-toko',
                'name' => 'Belanja, Toko & Menawar',
                'level' => 'daily',
                'icon' => '🛍️',
                'color_theme' => 'teal',
                'description' => 'Belanja di mall atau pasar, menanyakan ukuran pakaian, diskon, dan metode pembayaran.',
                'sort_order' => 5,
                'vocabularies' => [
                    [
                        'word' => 'Discount',
                        'phonetic' => '/ˈdɪs.kaʊnt/',
                        'part_of_speech' => 'Noun / Verb',
                        'translation' => 'Potongan harga / Diskon',
                        'example_sentence' => 'Is there any discount if I buy two items?',
                        'example_translation' => 'Apakah ada diskon jika saya membeli dua barang?',
                        'pronunciation_tip' => 'DIS-kaunt.',
                        'difficulty' => 'daily',
                    ],
                    [
                        'word' => 'Fitting room',
                        'phonetic' => '/ˈfɪt.ɪŋ ruːm/',
                        'part_of_speech' => 'Noun',
                        'translation' => 'Kamar pas / Ruang coba baju',
                        'example_sentence' => 'Where is the fitting room? I want to try this jacket on.',
                        'example_translation' => 'Di mana kamar pas? Saya ingin mencoba jaket ini.',
                        'pronunciation_tip' => 'FIT-ing room.',
                        'difficulty' => 'daily',
                    ],
                    [
                        'word' => 'Affordable',
                        'phonetic' => '/əˈfɔːr.də.bəl/',
                        'part_of_speech' => 'Adjective',
                        'translation' => 'Terjangkau harganya / Murah meriah berkualitas',
                        'example_sentence' => 'Their prices are very affordable compared to other brands.',
                        'example_translation' => 'Harga mereka sangat terjangkau dibanding merek lain.',
                        'pronunciation_tip' => 'ə-FOR-də-bl.',
                        'difficulty' => 'daily',
                    ],
                    [
                        'word' => 'Receipt',
                        'phonetic' => '/rɪˈsiːt/',
                        'part_of_speech' => 'Noun',
                        'translation' => 'Struk pembayaran / Tanda terima',
                        'example_sentence' => 'Keep the receipt in case you want an exchange.',
                        'example_translation' => 'Simpan struknya jika kamu ingin menukar barang nanti.',
                        'pronunciation_tip' => 'Huruf \'p\' TIDAK dibaca: \'ri-SEET\'.',
                        'difficulty' => 'daily',
                    ],
                    [
                        'word' => 'Refund',
                        'phonetic' => '/ˈriː.fʌnd/',
                        'part_of_speech' => 'Noun / Verb',
                        'translation' => 'Pengembalian uang',
                        'example_sentence' => 'Can I get a full refund if the product is damaged?',
                        'example_translation' => 'Bisakah saya mendapat pengembalian uang penuh bila produk rusak?',
                        'pronunciation_tip' => 'REE-fand.',
                        'difficulty' => 'daily',
                    ],
                ],
            ],
            [
                'slug' => 'arah-dan-perjalanan',
                'name' => 'Arah Jalan, Bandara & Transportasi',
                'level' => 'daily',
                'icon' => '🧭',
                'color_theme' => 'cyan',
                'description' => 'Navigasi di luar negeri, naik kereta/pesawat, bertanya jalan kepada pejalan kaki.',
                'sort_order' => 6,
                'vocabularies' => [
                    [
                        'word' => 'Excuse me, how do I get to...?',
                        'phonetic' => '/ɪkˈskjuːz miː haʊ duː aɪ ɡet tuː/',
                        'part_of_speech' => 'Phrase',
                        'translation' => 'Permisi, bagaimana cara saya menuju ke...?',
                        'example_sentence' => 'Excuse me, how do I get to the central station?',
                        'example_translation' => 'Permisi, bagaimana cara saya menuju ke stasiun pusat?',
                        'pronunciation_tip' => 'Ik-SKYOOZ mee.',
                        'difficulty' => 'daily',
                    ],
                    [
                        'word' => 'Turn left / Turn right',
                        'phonetic' => '/tɜːrn left / tɜːrn raɪt/',
                        'part_of_speech' => 'Phrase',
                        'translation' => 'Belok kiri / Belok kanan',
                        'example_sentence' => 'Go straight ahead, then turn right at the traffic light.',
                        'example_translation' => 'Lurus saja, kemudian belok kanan di lampu merah.',
                        'pronunciation_tip' => 'Tern left / Tern rait.',
                        'difficulty' => 'daily',
                    ],
                    [
                        'word' => 'Departure',
                        'phonetic' => '/dɪˈpɑːr.tʃər/',
                        'part_of_speech' => 'Noun',
                        'translation' => 'Keberangkatan',
                        'example_sentence' => 'The flight departure is delayed by twenty minutes.',
                        'example_translation' => 'Keberangkatan penerbangan tertunda selama 20 menit.',
                        'pronunciation_tip' => 'Di-PAR-cher.',
                        'difficulty' => 'daily',
                    ],
                    [
                        'word' => 'Boarding pass',
                        'phonetic' => '/ˈbɔːr.dɪŋ pæs/',
                        'part_of_speech' => 'Noun',
                        'translation' => 'Tiket naik pesawat / Kapal',
                        'example_sentence' => 'Have your passport and boarding pass ready.',
                        'example_translation' => 'Siapkan paspor dan boarding pass Anda.',
                        'pronunciation_tip' => 'BOR-ding pass.',
                        'difficulty' => 'daily',
                    ],
                    [
                        'word' => 'Crossroad',
                        'phonetic' => '/ˈkrɒs.roʊd/',
                        'part_of_speech' => 'Noun',
                        'translation' => 'Persimpangan jalan / Perempatan',
                        'example_sentence' => 'The museum is just across the crossroad.',
                        'example_translation' => 'Museum tersebut tepat berada di seberang persimpangan jalan.',
                        'pronunciation_tip' => 'KROSS-rohd.',
                        'difficulty' => 'daily',
                    ],
                ],
            ],
            [
                'slug' => 'idiom-frasa-populer',
                'name' => 'Idiom & Ungkapan Mahir',
                'level' => 'advanced',
                'icon' => '💡',
                'color_theme' => 'fuchsia',
                'description' => 'Frasa kiasan yang digunakan native speaker agar bahasa Inggris terdengar luwes dan alami.',
                'sort_order' => 7,
                'vocabularies' => [
                    [
                        'word' => 'Piece of cake',
                        'phonetic' => '/piːs əv keɪk/',
                        'part_of_speech' => 'Idiom',
                        'translation' => 'Sangat mudah sekali / Gampang banget',
                        'example_sentence' => 'Don\'t worry about the grammar quiz, it was a piece of cake!',
                        'example_translation' => 'Jangan khawatir tentang kuis tata bahasa itu, gampang banget kok!',
                        'pronunciation_tip' => 'Sambungkan suara: \'peesa-keik\'.',
                        'difficulty' => 'advanced',
                    ],
                    [
                        'word' => 'Hit the nail on the head',
                        'phonetic' => '/hɪt ðə neɪl ɒn ðə hed/',
                        'part_of_speech' => 'Idiom',
                        'translation' => 'Tepat sasaran / Pendapat yang sangat akurat',
                        'example_sentence' => 'Your analysis hit the nail on the head.',
                        'example_translation' => 'Analisis yang kamu berikan benar-benar tepat sasaran.',
                        'pronunciation_tip' => 'Ucapkan mengalir lancar dalam satu hembusan napas.',
                        'difficulty' => 'advanced',
                    ],
                    [
                        'word' => 'Under the weather',
                        'phonetic' => '/ˈʌn.dər ðə ˈweð.ər/',
                        'part_of_speech' => 'Idiom',
                        'translation' => 'Kurang enak badan / Masuk angin',
                        'example_sentence' => 'I cannot join the team dinner tonight; I feel a bit under the weather.',
                        'example_translation' => 'Saya tidak bisa ikut makan malam tim malam ini; saya merasa agak kurang enak badan.',
                        'pronunciation_tip' => 'AN-der the WE-ther.',
                        'difficulty' => 'advanced',
                    ],
                    [
                        'word' => 'Once in a blue moon',
                        'phonetic' => '/wʌns ɪn ə bluː muːn/',
                        'part_of_speech' => 'Idiom',
                        'translation' => 'Sangat jarang sekali terjadi',
                        'example_sentence' => 'He only visits his hometown once in a blue moon.',
                        'example_translation' => 'Dia sangat jarang sekali pulang ke kampung halamannya.',
                        'pronunciation_tip' => 'Wan-sin-a-bloo-moon.',
                        'difficulty' => 'advanced',
                    ],
                    [
                        'word' => 'Break a leg',
                        'phonetic' => '/breɪk ə leɡ/',
                        'part_of_speech' => 'Idiom',
                        'translation' => 'Semoga sukses / Tampil hebat ya! (bukan patah kaki)',
                        'example_sentence' => 'You will do great in your speech today, break a leg!',
                        'example_translation' => 'Kamu pasti tampil luar biasa dalam pidatomu hari ini, semoga sukses ya!',
                        'pronunciation_tip' => 'Breik-a-leg.',
                        'difficulty' => 'advanced',
                    ],
                    [
                        'word' => 'Cost an arm and a leg',
                        'phonetic' => '/kɒst ən ɑːrm ænd ə leɡ/',
                        'part_of_speech' => 'Idiom',
                        'translation' => 'Mahal sekali / Menguras kantong',
                        'example_sentence' => 'Buying a sports car in Singapore costs an arm and a leg.',
                        'example_translation' => 'Membeli mobil sport di Singapura luar biasa mahal.',
                        'pronunciation_tip' => 'Kost an arm and a leg.',
                        'difficulty' => 'advanced',
                    ],
                ],
            ],
            [
                'slug' => 'bisnis-kantor-interview',
                'name' => 'Bisnis, Kantor & Wawancara Kerja',
                'level' => 'advanced',
                'icon' => '💼',
                'color_theme' => 'sky',
                'description' => 'Komunikasi profesional, presentasi, negosiasi gaji, dan menjawab pertanyaan wawancara.',
                'sort_order' => 8,
                'vocabularies' => [
                    [
                        'word' => 'Negotiation',
                        'phonetic' => '/nɪˌɡoʊ.ʃiˈeɪ.ʃən/',
                        'part_of_speech' => 'Noun',
                        'translation' => 'Negosiasi / Perundingan',
                        'example_sentence' => 'Both parties reached an agreement after a lengthy negotiation.',
                        'example_translation' => 'Kedua belah pihak mencapai kesepakatan setelah negosiasi yang panjang.',
                        'pronunciation_tip' => 'Ni-go-shee-EI-shən.',
                        'difficulty' => 'advanced',
                    ],
                    [
                        'word' => 'Deliverable',
                        'phonetic' => '/dɪˈlɪv.ər.ə.bəl/',
                        'part_of_speech' => 'Noun',
                        'translation' => 'Hasil kerja / Output yang harus diserahkan',
                        'example_sentence' => 'We need to submit the final project deliverables by Friday.',
                        'example_translation' => 'Kita harus menyerahkan hasil kerja proyek final paling lambat hari Jumat.',
                        'pronunciation_tip' => 'Di-LIV-er-a-bl.',
                        'difficulty' => 'advanced',
                    ],
                    [
                        'word' => 'Strength and weakness',
                        'phonetic' => '/streŋθ ænd ˈwiːk.nəs/',
                        'part_of_speech' => 'Phrase',
                        'translation' => 'Kekuatan dan kelemahan diri',
                        'example_sentence' => 'What do you consider your greatest professional strength?',
                        'example_translation' => 'Apa yang Anda anggap sebagai kekuatan profesional terbesar Anda?',
                        'pronunciation_tip' => 'Streng-th and week-nəs.',
                        'difficulty' => 'advanced',
                    ],
                    [
                        'word' => 'Collaborate',
                        'phonetic' => '/kəˈlæb.ə.reɪt/',
                        'part_of_speech' => 'Verb',
                        'translation' => 'Bekerja sama / Berkolaborasi',
                        'example_sentence' => 'Our team collaborated closely with international engineers.',
                        'example_translation' => 'Tim kami berkolaborasi erat dengan para insinyur internasional.',
                        'pronunciation_tip' => 'Kə-LA-bə-reit.',
                        'difficulty' => 'advanced',
                    ],
                    [
                        'word' => 'Deadline',
                        'phonetic' => '/ˈded.laɪn/',
                        'part_of_speech' => 'Noun',
                        'translation' => 'Batas waktu / Tenggat waktu',
                        'example_sentence' => 'We managed to finish the prototype ahead of the deadline.',
                        'example_translation' => 'Kami berhasil menyelesaikan purwarupa lebih awal dari tenggat waktu.',
                        'pronunciation_tip' => 'DED-lain.',
                        'difficulty' => 'advanced',
                    ],
                ],
            ],
            [
                'slug' => 'darurat-medis-kesehatan',
                'name' => 'Situasi Darurat & Dokter',
                'level' => 'advanced',
                'icon' => '🏥',
                'color_theme' => 'red',
                'description' => 'Cara meminta pertolongan pertama, menjelaskan gejala penyakit kepada dokter, dan menelepon ambulans.',
                'sort_order' => 9,
                'vocabularies' => [
                    [
                        'word' => 'Emergency',
                        'phonetic' => '/ɪˈmɜːr.dʒən.si/',
                        'part_of_speech' => 'Noun',
                        'translation' => 'Keadaan darurat',
                        'example_sentence' => 'In case of an emergency, please dial 911 immediately.',
                        'example_translation' => 'Jika dalam keadaan darurat, mohon segera hubungi 911.',
                        'pronunciation_tip' => 'I-MER-jən-see.',
                        'difficulty' => 'advanced',
                    ],
                    [
                        'word' => 'Symptom',
                        'phonetic' => '/ˈsɪmp.təm/',
                        'part_of_speech' => 'Noun',
                        'translation' => 'Gejala penyakit',
                        'example_sentence' => 'What specific symptoms have you been experiencing?',
                        'example_translation' => 'Gejala spesifik apa saja yang sedang Anda rasakan?',
                        'pronunciation_tip' => 'SIMP-təm. Huruf \'p\' berbunyi tipis.',
                        'difficulty' => 'advanced',
                    ],
                    [
                        'word' => 'Prescription',
                        'phonetic' => '/prɪˈskrɪp.ʃən/',
                        'part_of_speech' => 'Noun',
                        'translation' => 'Resep obat dokter',
                        'example_sentence' => 'You can redeem this prescription at any 24-hour pharmacy.',
                        'example_translation' => 'Anda dapat menebus resep ini di apotek 24 jam mana pun.',
                        'pronunciation_tip' => 'Pri-SKRIP-shən.',
                        'difficulty' => 'advanced',
                    ],
                    [
                        'word' => 'Dizzy',
                        'phonetic' => '/ˈdɪz.i/',
                        'part_of_speech' => 'Adjective',
                        'translation' => 'Pusing / Kleyengan',
                        'example_sentence' => 'I feel suddenly dizzy when I stand up quickly.',
                        'example_translation' => 'Saya mendadak merasa pusing saat berdiri cepat.',
                        'pronunciation_tip' => 'DI-zee.',
                        'difficulty' => 'advanced',
                    ],
                ],
            ],
            [
                'slug' => 'keluarga-dan-perasaan',
                'name' => 'Keluarga, Emosi & Perasaan',
                'level' => 'beginner',
                'icon' => '💖',
                'color_theme' => 'pink',
                'description' => 'Mengekspresikan rasa syukur, bahagia, lelah, dan mendeskripsikan orang-orang terdekat.',
                'sort_order' => 10,
                'vocabularies' => [
                    [
                        'word' => 'Grateful',
                        'phonetic' => '/ˈɡreɪt.fəl/',
                        'part_of_speech' => 'Adjective',
                        'translation' => 'Bersyukur / Berterima kasih',
                        'example_sentence' => 'I am truly grateful for your encouragement and support.',
                        'example_translation' => 'Saya sangat bersyukur atas dorongan dan dukunganmu.',
                        'pronunciation_tip' => 'GREIT-fəl.',
                        'difficulty' => 'basic',
                    ],
                    [
                        'word' => 'Sibling',
                        'phonetic' => '/ˈsɪb.lɪŋ/',
                        'part_of_speech' => 'Noun',
                        'translation' => 'Saudara kandung (kakak / adik)',
                        'example_sentence' => 'Do you have any brothers, sisters, or other siblings?',
                        'example_translation' => 'Apakah kamu memiliki saudara kandung laki-laki atau perempuan?',
                        'pronunciation_tip' => 'SIB-ling.',
                        'difficulty' => 'basic',
                    ],
                    [
                        'word' => 'Excited',
                        'phonetic' => '/ɪkˈsaɪ.tɪd/',
                        'part_of_speech' => 'Adjective',
                        'translation' => 'Sangat bersemangat / Antusias',
                        'example_sentence' => 'The children are so excited about their holiday trip.',
                        'example_translation' => 'Anak-anak sangat antusias menyambut liburan mereka.',
                        'pronunciation_tip' => 'Ik-SAI-tid.',
                        'difficulty' => 'basic',
                    ],
                    [
                        'word' => 'Exhausted',
                        'phonetic' => '/ɪɡˈzɔː.stɪd/',
                        'part_of_speech' => 'Adjective',
                        'translation' => 'Sangat lelah / Capek sekali',
                        'example_sentence' => 'After working overtime for ten hours, she was utterly exhausted.',
                        'example_translation' => 'Setelah bekerja lembur selama 10 jam, dia benar-benar kelelahan.',
                        'pronunciation_tip' => 'Ig-ZAWS-tid.',
                        'difficulty' => 'daily',
                    ],
                    [
                        'word' => 'Celebrate',
                        'phonetic' => '/ˈsel.ə.breɪt/',
                        'part_of_speech' => 'Verb',
                        'translation' => 'Merayakan',
                        'example_sentence' => 'Let us gather together to celebrate your success!',
                        'example_translation' => 'Mari kita berkumpul untuk merayakan kesuksesanmu!',
                        'pronunciation_tip' => 'SEL-ə-breit.',
                        'difficulty' => 'basic',
                    ],
                ],
            ],
            [
                'slug' => 'hotel-dan-akomodasi',
                'name' => 'Hotel & Akomodasi Liburan',
                'level' => 'daily',
                'icon' => '🏨',
                'color_theme' => 'indigo',
                'description' => 'Check-in kamar, konfirmasi reservasi, meminta amenities, dan info sarapan pagi.',
                'sort_order' => 11,
                'vocabularies' => [
                    [
                        'word' => 'Reservation',
                        'phonetic' => '/ˌrez.ɚˈveɪ.ʃən/',
                        'part_of_speech' => 'Noun',
                        'translation' => 'Reservasi / Pemesanan tempat',
                        'example_sentence' => 'I have a room reservation under the name Hartanto.',
                        'example_translation' => 'Saya memiliki reservasi kamar atas nama Hartanto.',
                        'pronunciation_tip' => 'Re-zer-VEI-shən.',
                        'difficulty' => 'daily',
                    ],
                    [
                        'word' => 'Baggage',
                        'phonetic' => '/ˈbæɡ.ɪdʒ/',
                        'part_of_speech' => 'Noun',
                        'translation' => 'Koper / Barang bawaan (Bagasi)',
                        'example_sentence' => 'Can we leave our baggage at the reception until check-in time?',
                        'example_translation' => 'Bisakah kami menitipkan koper di resepsionis sampai waktu check-in tiba?',
                        'pronunciation_tip' => 'BA-gij.',
                        'difficulty' => 'daily',
                    ],
                    [
                        'word' => 'Amenities',
                        'phonetic' => '/əˈmen.ə.t̬iz/',
                        'part_of_speech' => 'Noun',
                        'translation' => 'Fasilitas pelengkap (kolam renang, gym, perlengkapan mandi)',
                        'example_sentence' => 'The hotel provides complimentary amenities including high-speed Wi-Fi.',
                        'example_translation' => 'Hotel menyediakan fasilitas gratis termasuk Wi-Fi berkecepatan tinggi.',
                        'pronunciation_tip' => 'ə-MEN-ə-teez.',
                        'difficulty' => 'daily',
                    ],
                    [
                        'word' => 'Wake-up call',
                        'phonetic' => '/ˈweɪk.ʌp kɔːl/',
                        'part_of_speech' => 'Noun',
                        'translation' => 'Panggilan bangun pagi dari hotel',
                        'example_sentence' => 'Could I request a wake-up call tomorrow at six o\'clock?',
                        'example_translation' => 'Bisakah saya meminta panggilan bangun pagi besok jam enam tepat?',
                        'pronunciation_tip' => 'Weik-ap kawl.',
                        'difficulty' => 'daily',
                    ],
                ],
            ],
            [
                'slug' => 'slang-ungkapan-gaul',
                'name' => 'Slang & Percakapan Santai Gaul',
                'level' => 'advanced',
                'icon' => '🔥',
                'color_theme' => 'amber',
                'description' => 'Frasa kasual yang sering dipakai anak muda & native speaker dalam obrolan sehari-hari.',
                'sort_order' => 12,
                'vocabularies' => [
                    [
                        'word' => 'No worries',
                        'phonetic' => '/noʊ ˈwʌr.iz/',
                        'part_of_speech' => 'Phrase / Slang',
                        'translation' => 'Tidak apa-apa / Santai saja / Sama-sama',
                        'example_sentence' => 'Thanks for the ride! - No worries, happy to help!',
                        'example_translation' => 'Terima kasih atas tumpangannya! - Santai saja, senang bisa membantu!',
                        'pronunciation_tip' => 'Noh WUR-eez.',
                        'difficulty' => 'daily',
                    ],
                    [
                        'word' => 'Chill out',
                        'phonetic' => '/tʃɪl aʊt/',
                        'part_of_speech' => 'Phrasal Verb',
                        'translation' => 'Santai / Rileks / Mendinginkan pikiran',
                        'example_sentence' => 'Let us just stay at home this weekend and chill out.',
                        'example_translation' => 'Ayo kita di rumah saja akhir pekan ini dan santai rileks.',
                        'pronunciation_tip' => 'Chil-aut.',
                        'difficulty' => 'daily',
                    ],
                    [
                        'word' => 'Catch up',
                        'phonetic' => '/kætʃ ʌp/',
                        'part_of_speech' => 'Phrasal Verb',
                        'translation' => 'Bertemu untuk saling cerita kabar terkini',
                        'example_sentence' => 'We haven\'t seen each other in ages, let us catch up over coffee!',
                        'example_translation' => 'Kita sudah lama tidak saling jumpa, ayo ngobrol sambil ngopi!',
                        'pronunciation_tip' => 'Kach-ap.',
                        'difficulty' => 'daily',
                    ],
                    [
                        'word' => 'For real',
                        'phonetic' => '/fɔːr rɪəl/',
                        'part_of_speech' => 'Idiom / Slang',
                        'translation' => 'Beneran / Serius nih?',
                        'example_sentence' => 'Did you get the promotion for real? Congratulations!',
                        'example_translation' => 'Kamu beneran dapet promosi jabatan itu? Selamat ya!',
                        'pronunciation_tip' => 'Fer-REEL.',
                        'difficulty' => 'advanced',
                    ],
                ],
            ],
            [
                'slug' => 'warna-bentuk-deskripsi',
                'name' => 'Warna, Bentuk & Deskripsi',
                'level' => 'beginner',
                'icon' => '🎨',
                'color_theme' => 'fuchsia',
                'description' => 'Mendeskripsikan benda, ukuran ruangan, warna cerah, dan penampilan fisik secara akurat.',
                'sort_order' => 13,
                'vocabularies' => [
                    [
                        'word' => 'Enormous',
                        'phonetic' => '/ɪˈnɔːr.məs/',
                        'part_of_speech' => 'Adjective',
                        'translation' => 'Sangat besar sekali / Raksasa',
                        'example_sentence' => 'They live in an enormous house near the lake.',
                        'example_translation' => 'Mereka tinggal di rumah yang sangat besar di dekat danau.',
                        'pronunciation_tip' => 'I-NOR-məs.',
                        'difficulty' => 'basic',
                    ],
                    [
                        'word' => 'Tiny',
                        'phonetic' => '/ˈtaɪ.ni/',
                        'part_of_speech' => 'Adjective',
                        'translation' => 'Sangat kecil / Mungil',
                        'example_sentence' => 'Even a tiny mistake can affect the whole result.',
                        'example_translation' => 'Bahkan kesalahan kecil mungil pun bisa mempengaruhi seluruh hasil.',
                        'pronunciation_tip' => 'TAI-nee.',
                        'difficulty' => 'basic',
                    ],
                    [
                        'word' => 'Bright',
                        'phonetic' => '/braɪt/',
                        'part_of_speech' => 'Adjective',
                        'translation' => 'Terang / Cemerlang / Cerdas',
                        'example_sentence' => 'She has a bright future ahead of her.',
                        'example_translation' => 'Dia memiliki masa depan yang cerah di depannya.',
                        'pronunciation_tip' => 'Brait.',
                        'difficulty' => 'basic',
                    ],
                    [
                        'word' => 'Circle',
                        'phonetic' => '/ˈsɜːr.kəl/',
                        'part_of_speech' => 'Noun',
                        'translation' => 'Lingkaran / Bundaran',
                        'example_sentence' => 'Please sit in a circle so everyone can see each other.',
                        'example_translation' => 'Silakan duduk melingkar agar semua orang bisa saling melihat.',
                        'pronunciation_tip' => 'SER-kl.',
                        'difficulty' => 'basic',
                    ],
                    [
                        'word' => 'Narrow',
                        'phonetic' => '/ˈnær.oʊ/',
                        'part_of_speech' => 'Adjective',
                        'translation' => 'Sempit',
                        'example_sentence' => 'The car could not pass through the narrow alley.',
                        'example_translation' => 'Mobil itu tidak bisa melewati gang yang sempit tersebut.',
                        'pronunciation_tip' => 'NA-roh.',
                        'difficulty' => 'daily',
                    ],
                    [
                        'word' => 'Gorgeous',
                        'phonetic' => '/ˈɡɔːr.dʒəs/',
                        'part_of_speech' => 'Adjective',
                        'translation' => 'Sangat indah / Menawan luar biasa',
                        'example_sentence' => 'The sunset over the ocean looks absolutely gorgeous.',
                        'example_translation' => 'Matahari terbenam di atas lautan terlihat sangat menawan luar biasa.',
                        'pronunciation_tip' => 'GOR-jəs.',
                        'difficulty' => 'daily',
                    ],
                ],
            ],
            [
                'slug' => 'rumah-dan-aktivitas',
                'name' => 'Rumah, Perabot & Aktivitas',
                'level' => 'beginner',
                'icon' => '🏠',
                'color_theme' => 'amber',
                'description' => 'Nama ruangan, perlengkapan tempat tidur, perabot dapur, dan kegiatan membersihkan rumah.',
                'sort_order' => 14,
                'vocabularies' => [
                    [
                        'word' => 'Kitchen',
                        'phonetic' => '/ˈkɪtʃ.ən/',
                        'part_of_speech' => 'Noun',
                        'translation' => 'Dapur',
                        'example_sentence' => 'My mother is preparing breakfast in the kitchen.',
                        'example_translation' => 'Ibu saya sedang menyiapkan sarapan di dapur.',
                        'pronunciation_tip' => 'KICH-ən.',
                        'difficulty' => 'basic',
                    ],
                    [
                        'word' => 'Bedroom',
                        'phonetic' => '/ˈbed.rʊm/',
                        'part_of_speech' => 'Noun',
                        'translation' => 'Kamar tidur',
                        'example_sentence' => 'The master bedroom has a private balcony.',
                        'example_translation' => 'Kamar tidur utama memiliki balkon pribadi.',
                        'pronunciation_tip' => 'BED-room.',
                        'difficulty' => 'basic',
                    ],
                    [
                        'word' => 'Appliance',
                        'phonetic' => '/əˈplaɪ.əns/',
                        'part_of_speech' => 'Noun',
                        'translation' => 'Peralatan elektronik rumah tangga',
                        'example_sentence' => 'Modern kitchen appliances save a lot of time and energy.',
                        'example_translation' => 'Peralatan elektronik dapur modern menghemat banyak waktu dan energi.',
                        'pronunciation_tip' => 'ə-PLAI-əns.',
                        'difficulty' => 'daily',
                    ],
                    [
                        'word' => 'Tidy up',
                        'phonetic' => '/ˈtaɪ.di ʌp/',
                        'part_of_speech' => 'Phrasal Verb',
                        'translation' => 'Merapikan / Membereskan barang',
                        'example_sentence' => 'Let us tidy up the living room before the guests arrive.',
                        'example_translation' => 'Mari kita bereskan ruang tamu sebelum tamu tiba.',
                        'pronunciation_tip' => 'TAI-dee ap.',
                        'difficulty' => 'basic',
                    ],
                    [
                        'word' => 'Sweep',
                        'phonetic' => '/swiːp/',
                        'part_of_speech' => 'Verb',
                        'translation' => 'Menyapu lantai',
                        'example_sentence' => 'I sweep the floor every morning to keep it clean.',
                        'example_translation' => 'Saya menyapu lantai setiap pagi agar tetap bersih.',
                        'pronunciation_tip' => 'Sweeep.',
                        'difficulty' => 'basic',
                    ],
                    [
                        'word' => 'Blanket',
                        'phonetic' => '/ˈblæŋ.kɪt/',
                        'part_of_speech' => 'Noun',
                        'translation' => 'Selimut hangat',
                        'example_sentence' => 'Could you bring me an extra blanket? It is cold tonight.',
                        'example_translation' => 'Bisakah Anda membawakan saya selimut tambahan? Malam ini dingin.',
                        'pronunciation_tip' => 'BLANG-kit.',
                        'difficulty' => 'basic',
                    ],
                ],
            ],
            [
                'slug' => 'cuaca-musim-alam',
                'name' => 'Cuaca, Musim & Suasana Alam',
                'level' => 'beginner',
                'icon' => '⛅',
                'color_theme' => 'sky',
                'description' => 'Membicarakan prakiraan cuaca, hujan gerimis, badai petir, suhu dingin, dan musim.',
                'sort_order' => 15,
                'vocabularies' => [
                    [
                        'word' => 'Sunny',
                        'phonetic' => '/ˈsʌn.i/',
                        'part_of_speech' => 'Adjective',
                        'translation' => 'Cerah / Terik berawan cerah',
                        'example_sentence' => 'It is a lovely sunny day for an outdoor picnic.',
                        'example_translation' => 'Hari ini hari yang cerah menyenangkan untuk piknik di luar ruangan.',
                        'pronunciation_tip' => 'SAN-ee.',
                        'difficulty' => 'basic',
                    ],
                    [
                        'word' => 'Drizzle',
                        'phonetic' => '/ˈdrɪz.əl/',
                        'part_of_speech' => 'Noun / Verb',
                        'translation' => 'Hujan gerimis rintik-rintik',
                        'example_sentence' => 'Take an umbrella; it started to drizzle outside.',
                        'example_translation' => 'Bawalah payung; di luar sudah mulai gerimis.',
                        'pronunciation_tip' => 'DRIZ-l.',
                        'difficulty' => 'daily',
                    ],
                    [
                        'word' => 'Thunderstorm',
                        'phonetic' => '/ˈθʌn.dər.stɔːrm/',
                        'part_of_speech' => 'Noun',
                        'translation' => 'Badai petir & kilat lebat',
                        'example_sentence' => 'The flight was grounded due to a severe thunderstorm.',
                        'example_translation' => 'Penerbangan ditunda karena badai petir yang parah.',
                        'pronunciation_tip' => 'THAN-der-storm (th tipis).',
                        'difficulty' => 'daily',
                    ],
                    [
                        'word' => 'Breeze',
                        'phonetic' => '/briːz/',
                        'part_of_speech' => 'Noun',
                        'translation' => 'Angin sepoi-sepoi yang sejuk',
                        'example_sentence' => 'A gentle breeze blew across the beach in the evening.',
                        'example_translation' => 'Angin sepoi-sepoi yang lembut berhembus di sepanjang pantai pada sore hari.',
                        'pronunciation_tip' => 'Breeez.',
                        'difficulty' => 'daily',
                    ],
                    [
                        'word' => 'Freezing',
                        'phonetic' => '/ˈfriː.zɪŋ/',
                        'part_of_speech' => 'Adjective',
                        'translation' => 'Sangat dingin membeku',
                        'example_sentence' => 'Put on your thick jacket; it is freezing out there!',
                        'example_translation' => 'Pakailah jaket tebalmu; udara di luar sangat dingin membeku!',
                        'pronunciation_tip' => 'FREE-zing.',
                        'difficulty' => 'daily',
                    ],
                    [
                        'word' => 'Humidity',
                        'phonetic' => '/hjuːˈmɪd.ə.t̬i/',
                        'part_of_speech' => 'Noun',
                        'translation' => 'Kelembapan udara',
                        'example_sentence' => 'Tropical countries typically have very high humidity.',
                        'example_translation' => 'Negara-negara tropis biasanya memiliki kelembapan udara yang sangat tinggi.',
                        'pronunciation_tip' => 'Hyoo-MID-ə-tee.',
                        'difficulty' => 'advanced',
                    ],
                ],
            ],
            [
                'slug' => 'pekerjaan-dan-profesi',
                'name' => 'Profesi, Karir & Dunia Kerja',
                'level' => 'daily',
                'icon' => '👨‍💼',
                'color_theme' => 'emerald',
                'description' => 'Nama profesi global, promosi jabatan, berkas resume kerja, dan interaksi dengan rekan kantor.',
                'sort_order' => 16,
                'vocabularies' => [
                    [
                        'word' => 'Software engineer',
                        'phonetic' => '/ˈsɒft.weər ˌen.dʒɪˈnɪər/',
                        'part_of_speech' => 'Noun',
                        'translation' => 'Insinyur perangkat lunak / Programmer',
                        'example_sentence' => 'She works as a lead software engineer at a tech startup.',
                        'example_translation' => 'Dia bekerja sebagai lead software engineer di perusahaan rintisan teknologi.',
                        'pronunciation_tip' => 'SOFT-wair en-ji-NEER.',
                        'difficulty' => 'daily',
                    ],
                    [
                        'word' => 'Entrepreneur',
                        'phonetic' => '/ˌɑːn.trə.prəˈnɝː/',
                        'part_of_speech' => 'Noun',
                        'translation' => 'Wirausahawan / Pebisnis mandiri',
                        'example_sentence' => 'Every successful entrepreneur takes calculated risks.',
                        'example_translation' => 'Setiap wirausahawan sukses mengambil risiko yang telah diperhitungkan.',
                        'pronunciation_tip' => 'Ahn-truh-pruh-NUR.',
                        'difficulty' => 'advanced',
                    ],
                    [
                        'word' => 'Accountant',
                        'phonetic' => '/əˈkaʊn.tənt/',
                        'part_of_speech' => 'Noun',
                        'translation' => 'Akuntan / Bagian keuangan audit',
                        'example_sentence' => 'The accountant will review our annual financial report.',
                        'example_translation' => 'Akuntan akan meninjau laporan keuangan tahunan kita.',
                        'pronunciation_tip' => 'ə-KOUN-tənt.',
                        'difficulty' => 'daily',
                    ],
                    [
                        'word' => 'Promotion',
                        'phonetic' => '/prəˈmoʊ.ʃən/',
                        'part_of_speech' => 'Noun',
                        'translation' => 'Kenaikan jabatan / Promosi',
                        'example_sentence' => 'He received a well-deserved promotion to team manager.',
                        'example_translation' => 'Dia mendapatkan kenaikan jabatan yang layak menjadi manajer tim.',
                        'pronunciation_tip' => 'Pruh-MOH-shən.',
                        'difficulty' => 'daily',
                    ],
                    [
                        'word' => 'Resume',
                        'phonetic' => '/ˈrez.ə.meɪ/',
                        'part_of_speech' => 'Noun',
                        'translation' => 'Daftar riwayat hidup (CV)',
                        'example_sentence' => 'Please upload your updated resume before the interview.',
                        'example_translation' => 'Mohon unggah riwayat hidup terbaru Anda sebelum wawancara.',
                        'pronunciation_tip' => 'REZ-oo-mei (berbeda dengan kata kerja resume = melanjutkan).',
                        'difficulty' => 'daily',
                    ],
                    [
                        'word' => 'Colleague',
                        'phonetic' => '/ˈkɒl.iːɡ/',
                        'part_of_speech' => 'Noun',
                        'translation' => 'Rekan kerja sekantor',
                        'example_sentence' => 'I discussed the proposal with my senior colleagues.',
                        'example_translation' => 'Saya mendiskusikan proposal tersebut dengan rekan kerja senior saya.',
                        'pronunciation_tip' => 'KOL-eeg (huruf u & e di akhir lebur).',
                        'difficulty' => 'daily',
                    ],
                ],
            ],
            [
                'slug' => 'teknologi-dan-gadget',
                'name' => 'Teknologi, Gadget & Internet',
                'level' => 'daily',
                'icon' => '💻',
                'color_theme' => 'blue',
                'description' => 'Istilah koneksi nirkabel, kata sandi, unduhan data, pengisian daya baterai, dan sistem online.',
                'sort_order' => 17,
                'vocabularies' => [
                    [
                        'word' => 'Wireless',
                        'phonetic' => '/ˈwaɪər.ləs/',
                        'part_of_speech' => 'Adjective',
                        'translation' => 'Nirkabel / Tanpa kabel (Wi-Fi/Bluetooth)',
                        'example_sentence' => 'These wireless earphones have excellent sound cancellation.',
                        'example_translation' => 'Earphone nirkabel ini memiliki peredam suara yang sangat bagus.',
                        'pronunciation_tip' => 'WAI-er-ləs.',
                        'difficulty' => 'daily',
                    ],
                    [
                        'word' => 'Password',
                        'phonetic' => '/ˈpæs.wɜːrd/',
                        'part_of_speech' => 'Noun',
                        'translation' => 'Kata sandi akun',
                        'example_sentence' => 'Make sure to create a strong password for your online account.',
                        'example_translation' => 'Pastikan membuat kata sandi yang kuat untuk akun online Anda.',
                        'pronunciation_tip' => 'PASS-werd.',
                        'difficulty' => 'basic',
                    ],
                    [
                        'word' => 'Charger',
                        'phonetic' => '/ˈtʃɑːr.dʒər/',
                        'part_of_speech' => 'Noun',
                        'translation' => 'Alat pengisi daya baterai',
                        'example_sentence' => 'Can I borrow your phone charger for thirty minutes?',
                        'example_translation' => 'Bolehkah saya meminjam charger ponselmu selama 30 menit?',
                        'pronunciation_tip' => 'CHAR-jer.',
                        'difficulty' => 'basic',
                    ],
                    [
                        'word' => 'Glitch',
                        'phonetic' => '/ɡlɪtʃ/',
                        'part_of_speech' => 'Noun',
                        'translation' => 'Gangguan teknis kecil pada sistem/aplikasi',
                        'example_sentence' => 'The software has a temporary glitch that will be fixed soon.',
                        'example_translation' => 'Perangkat lunak ini memiliki gangguan teknis sementara yang akan segera diperbaiki.',
                        'pronunciation_tip' => 'Glich.',
                        'difficulty' => 'daily',
                    ],
                    [
                        'word' => 'Download',
                        'phonetic' => '/ˈdaʊn.loʊd/',
                        'part_of_speech' => 'Verb / Noun',
                        'translation' => 'Mengunduh data dari internet',
                        'example_sentence' => 'You can download the course materials as PDF files.',
                        'example_translation' => 'Anda dapat mengunduh materi kursus sebagai file PDF.',
                        'pronunciation_tip' => 'DOWN-lohd.',
                        'difficulty' => 'basic',
                    ],
                    [
                        'word' => 'Battery life',
                        'phonetic' => '/ˈbæt̬.ɚ.i laɪf/',
                        'part_of_speech' => 'Noun',
                        'translation' => 'Daya tahan baterai',
                        'example_sentence' => 'This new smartphone model provides up to two days of battery life.',
                        'example_translation' => 'Model ponsel pintar baru ini menyediakan daya tahan baterai hingga dua hari.',
                        'pronunciation_tip' => 'BAT-ri laif.',
                        'difficulty' => 'daily',
                    ],
                ],
            ],
            [
                'slug' => 'phrasal-verbs-populer',
                'name' => 'Phrasal Verbs Wajib Sehari-hari',
                'level' => 'daily',
                'icon' => '🔄',
                'color_theme' => 'violet',
                'description' => 'Gabungan kata kerja + preposisi yang maknanya berubah total dan dipakai setiap saat oleh native.',
                'sort_order' => 18,
                'vocabularies' => [
                    [
                        'word' => 'Look forward to',
                        'phonetic' => '/lʊk ˈfɔːr.wɚd tuː/',
                        'part_of_speech' => 'Phrasal Verb',
                        'translation' => 'Sangat menanti-nantikan (dengan senang hati)',
                        'example_sentence' => 'I truly look forward to hearing from you soon.',
                        'example_translation' => 'Saya sungguh menanti-nantikan kabar baik dari Anda segera.',
                        'pronunciation_tip' => 'Luk FOR-werd too.',
                        'difficulty' => 'daily',
                    ],
                    [
                        'word' => 'Find out',
                        'phonetic' => '/faɪnd aʊt/',
                        'part_of_speech' => 'Phrasal Verb',
                        'translation' => 'Mengetahui / Menemukan informasi baru',
                        'example_sentence' => 'Let us check the website to find out the store opening hours.',
                        'example_translation' => 'Mari kita periksa situs web untuk mengetahui jam buka toko.',
                        'pronunciation_tip' => 'Faind-aut.',
                        'difficulty' => 'daily',
                    ],
                    [
                        'word' => 'Run out of',
                        'phonetic' => '/rʌn aʊt əv/',
                        'part_of_speech' => 'Phrasal Verb',
                        'translation' => 'Kehabisan pasokan (uang, waktu, bensin)',
                        'example_sentence' => 'We are running out of time, so let us wrap up the meeting.',
                        'example_translation' => 'Kita sedang kehabisan waktu, jadi mari kita sudahi rapat ini.',
                        'pronunciation_tip' => 'Ran-aut-əv.',
                        'difficulty' => 'daily',
                    ],
                    [
                        'word' => 'Give up',
                        'phonetic' => '/ɡɪv ʌp/',
                        'part_of_speech' => 'Phrasal Verb',
                        'translation' => 'Menyerah / Putus asa',
                        'example_sentence' => 'Never give up on your dreams, no matter how tough it gets.',
                        'example_translation' => 'Jangan pernah menyerah pada impianmu, betapapun berat perjuangannya.',
                        'pronunciation_tip' => 'Giv-ap.',
                        'difficulty' => 'basic',
                    ],
                    [
                        'word' => 'Turn down',
                        'phonetic' => '/tɜːrn daʊn/',
                        'part_of_speech' => 'Phrasal Verb',
                        'translation' => 'Menolak tawaran / Mengecilkan volume',
                        'example_sentence' => 'He decided to turn down the job offer due to long commute.',
                        'example_translation' => 'Dia memutuskan untuk menolak tawaran pekerjaan itu karena jarak perjalanan yang jauh.',
                        'pronunciation_tip' => 'Tern-down.',
                        'difficulty' => 'daily',
                    ],
                    [
                        'word' => 'Take care of',
                        'phonetic' => '/teɪk keər əv/',
                        'part_of_speech' => 'Phrasal Verb',
                        'translation' => 'Merawat / Menjaga / Menangani urusan',
                        'example_sentence' => 'Don\'t worry about the payment; I will take care of it.',
                        'example_translation' => 'Jangan khawatir tentang pembayarannya; saya yang akan mengurusnya.',
                        'pronunciation_tip' => 'Teik-kair-əv.',
                        'difficulty' => 'daily',
                    ],
                ],
            ],
            [
                'slug' => 'transisi-dan-konektor',
                'name' => 'Kata Transisi & Konektor Mahir',
                'level' => 'advanced',
                'icon' => '🔗',
                'color_theme' => 'cyan',
                'description' => 'Penghubung kalimat formal agar opini, esai, dan presentasi terdengar runut dan profesional.',
                'sort_order' => 19,
                'vocabularies' => [
                    [
                        'word' => 'Furthermore',
                        'phonetic' => '/ˌfɝː.ðɚˈmɔːr/',
                        'part_of_speech' => 'Adverb / Transition',
                        'translation' => 'Lebih lanjut lagi / Selain itu (formal)',
                        'example_sentence' => 'The software is user-friendly; furthermore, it offers 24/7 support.',
                        'example_translation' => 'Perangkat lunak ini mudah digunakan; lebih lanjut lagi, ia menawarkan dukungan 24 jam.',
                        'pronunciation_tip' => 'FUR-ther-mor.',
                        'difficulty' => 'advanced',
                    ],
                    [
                        'word' => 'However',
                        'phonetic' => '/haʊˈev.ɚ/',
                        'part_of_speech' => 'Adverb / Transition',
                        'translation' => 'Namun demikian / Akan tetapi',
                        'example_sentence' => 'We trained hard; however, our opponents played remarkably well.',
                        'example_translation' => 'Kami berlatih keras; namun demikian, lawan kami bermain sangat baik.',
                        'pronunciation_tip' => 'Hau-EV-er.',
                        'difficulty' => 'daily',
                    ],
                    [
                        'word' => 'Consequently',
                        'phonetic' => '/ˈkɑːn.sə.kwənt.li/',
                        'part_of_speech' => 'Adverb / Transition',
                        'translation' => 'Sebagai akibatnya / Oleh karena itu',
                        'example_sentence' => 'Sales doubled; consequently, the company expanded overseas.',
                        'example_translation' => 'Penjualan meningkat dua kali lipat; sebagai akibatnya, perusahaan berekspansi ke luar negeri.',
                        'pronunciation_tip' => 'KAHN-suh-kwent-lee.',
                        'difficulty' => 'advanced',
                    ],
                    [
                        'word' => 'In addition',
                        'phonetic' => '/ɪn əˈdɪʃ.ən/',
                        'part_of_speech' => 'Phrase / Transition',
                        'translation' => 'Di samping itu / Selain itu',
                        'example_sentence' => 'In addition to English, she also speaks fluent Mandarin.',
                        'example_translation' => 'Di samping bahasa Inggris, dia juga fasih berbicara bahasa Mandarin.',
                        'pronunciation_tip' => 'In-uh-DISH-ən.',
                        'difficulty' => 'daily',
                    ],
                    [
                        'word' => 'As a matter of fact',
                        'phonetic' => '/æz ə ˈmæt̬.ɚ əv fækt/',
                        'part_of_speech' => 'Phrase / Transition',
                        'translation' => 'Bahkan kenyataannya / Sebenarnya',
                        'example_sentence' => 'I know him well; as a matter of fact, we were college roommates.',
                        'example_translation' => 'Saya mengenalnya dengan baik; bahkan sebenarnya, kami dulu teman sekamar kuliah.',
                        'pronunciation_tip' => 'Az-uh-mat-ter-ov-fakt.',
                        'difficulty' => 'advanced',
                    ],
                    [
                        'word' => 'In order to',
                        'phonetic' => '/ɪn ˈɔːr.dɚ tuː/',
                        'part_of_speech' => 'Phrase / Conjunction',
                        'translation' => 'Agar / Untuk tujuan / Supaya',
                        'example_sentence' => 'You must practice speaking regularly in order to become fluent.',
                        'example_translation' => 'Anda harus berlatih berbicara secara teratur agar menjadi fasih.',
                        'pronunciation_tip' => 'In-OR-der-too.',
                        'difficulty' => 'daily',
                    ],
                ],
            ],
            [
                'slug' => 'karakter-dan-sikap',
                'name' => 'Karakter, Sikap & Kepribadian',
                'level' => 'advanced',
                'icon' => '🧠',
                'color_theme' => 'purple',
                'description' => 'Mendeskripsikan sifat seseorang, kepercayaan diri, kerendahan hati, dan ketulusan hati.',
                'sort_order' => 20,
                'vocabularies' => [
                    [
                        'word' => 'Confident',
                        'phonetic' => '/ˈkɑːn.fə.dənt/',
                        'part_of_speech' => 'Adjective',
                        'translation' => 'Percaya diri / Yakin',
                        'example_sentence' => 'She felt confident while delivering her keynote speech.',
                        'example_translation' => 'Dia merasa percaya diri saat membawakan pidato utamanya.',
                        'pronunciation_tip' => 'KAHN-fi-dənt.',
                        'difficulty' => 'daily',
                    ],
                    [
                        'word' => 'Humble',
                        'phonetic' => '/ˈhʌm.bəl/',
                        'part_of_speech' => 'Adjective',
                        'translation' => 'Rendah hati / Tidak sombong',
                        'example_sentence' => 'Despite his massive fame, the author remains humble.',
                        'example_translation' => 'Terlepas dari ketenarannya yang luar biasa, sang penulis tetap rendah hati.',
                        'pronunciation_tip' => 'HAM-bl.',
                        'difficulty' => 'daily',
                    ],
                    [
                        'word' => 'Generous',
                        'phonetic' => '/ˈdʒen.ər.əs/',
                        'part_of_speech' => 'Adjective',
                        'translation' => 'Dermawan / Murah hati / Suka memberi',
                        'example_sentence' => 'He made a generous donation to the local animal shelter.',
                        'example_translation' => 'Dia memberikan donasi yang sangat dermawan untuk penampungan hewan lokal.',
                        'pronunciation_tip' => 'JEN-er-əs.',
                        'difficulty' => 'daily',
                    ],
                    [
                        'word' => 'Stubborn',
                        'phonetic' => '/ˈstʌb.ɚn/',
                        'part_of_speech' => 'Adjective',
                        'translation' => 'Keras kepala / Gigih teguh pendirian',
                        'example_sentence' => 'He is too stubborn to admit that he made a mistake.',
                        'example_translation' => 'Dia terlalu keras kepala untuk mengakui bahwa dia membuat kesalahan.',
                        'pronunciation_tip' => 'STUB-ern.',
                        'difficulty' => 'advanced',
                    ],
                    [
                        'word' => 'Relieved',
                        'phonetic' => '/rɪˈliːvd/',
                        'part_of_speech' => 'Adjective',
                        'translation' => 'Lega / Tenang setelah khawatir',
                        'example_sentence' => 'I felt so relieved after passing my driving license exam.',
                        'example_translation' => 'Saya merasa sangat lega setelah lulus ujian surat izin mengemudi.',
                        'pronunciation_tip' => 'Ri-LEEVD.',
                        'difficulty' => 'advanced',
                    ],
                    [
                        'word' => 'Genuine',
                        'phonetic' => '/ˈdʒen.ju.ɪn/',
                        'part_of_speech' => 'Adjective',
                        'translation' => 'Tulus / Asli / Otentik',
                        'example_sentence' => 'Her genuine kindness touched everyone in the classroom.',
                        'example_translation' => 'Kebaikan hatinya yang tulus menyentuh semua orang di ruang kelas.',
                        'pronunciation_tip' => 'JEN-yoo-in (akhiran \'-in\', bukan \'-ain\').',
                        'difficulty' => 'advanced',
                    ],
                ],
            ],
        ];

        foreach ($categoriesData as $catData) {
            $vocabList = $catData['vocabularies'];
            unset($catData['vocabularies']);

            $category = LearningCategory::updateOrCreate(
                ['slug' => $catData['slug']],
                $catData
            );

            foreach ($vocabList as $v) {
                Vocabulary::updateOrCreate(
                    [
                        'category_id' => $category->id,
                        'word' => $v['word'],
                    ],
                    $v
                );
            }
        }

        // Seed realistic Interactive Conversations
        $conversations = [
            [
                'title' => 'Memesan Kopi & Kue di Cafe London',
                'level' => 'daily',
                'scenario_tag' => 'Cafe & Restoran',
                'description' => 'Praktikkan memesan minuman kesukaan, ukuran cangkir, pilihan susu, dan opsi takeaway.',
                'dialogue_script' => [
                    [
                        'speaker' => 'Barista',
                        'role' => 'partner',
                        'text' => 'Good afternoon! What can I get started for you today?',
                        'translation' => 'Selamat siang! Mau pesan apa hari ini?',
                        'audio_hint' => 'Nada ramah dan ceria khas barista lokal.',
                    ],
                    [
                        'speaker' => 'You',
                        'role' => 'user',
                        'text' => 'Hi! Could I please get a regular iced caramel macchiato with oat milk?',
                        'translation' => 'Hai! Bisakah saya pesan satu iced caramel macchiato ukuran biasa dengan susu oat?',
                        'audio_hint' => 'Tekankan kata "regular" dan "oat milk".',
                    ],
                    [
                        'speaker' => 'Barista',
                        'role' => 'partner',
                        'text' => 'Sure thing! Would you like any pastries or sandwiches with that?',
                        'translation' => 'Tentu saja! Mau sekalian pesan pastry atau roti lapis?',
                        'audio_hint' => 'Penawaran tambahan ramah.',
                    ],
                    [
                        'speaker' => 'You',
                        'role' => 'user',
                        'text' => 'Just a warm blueberry muffin, please. Is it for here or takeaway?',
                        'translation' => 'Cukup satu muffin blueberry hangat. Apakah untuk makan di sini atau bawa pulang?',
                        'audio_hint' => 'Tanyakan dengan sopan.',
                    ],
                    [
                        'speaker' => 'Barista',
                        'role' => 'partner',
                        'text' => 'That will be for takeaway. Your total is eight pounds fifty. Contactless card is fine!',
                        'translation' => 'Akan dibungkus bawa pulang ya. Totalnya delapan pound lima puluh. Bisa bayar nontunai/kartu!',
                        'audio_hint' => 'Menyebutkan total harga.',
                    ],
                    [
                        'speaker' => 'You',
                        'role' => 'user',
                        'text' => 'Here you go. Thank you so much, have a wonderful day!',
                        'translation' => 'Ini kartunya. Terima kasih banyak, semoga harimu menyenangkan!',
                        'audio_hint' => 'Ungkapan penutup yang sangat disukai penutur asli.',
                    ],
                ],
            ],
            [
                'title' => 'Menanyakan Arah ke Stasiun Kereta Bawah Tanah',
                'level' => 'daily',
                'scenario_tag' => 'Travel & Commute',
                'description' => 'Tersesat di kota metropolitan dan meminta petunjuk arah dengan sopan kepada penduduk lokal.',
                'dialogue_script' => [
                    [
                        'speaker' => 'You',
                        'role' => 'user',
                        'text' => 'Excuse me, sorry to bother you! Could you tell me where the nearest metro station is?',
                        'translation' => 'Permisi, maaf mengganggu! Bisakah Anda memberi tahu di mana stasiun metro terdekat?',
                        'audio_hint' => 'Ucapkan "Excuse me" dengan nada sopan.',
                    ],
                    [
                        'speaker' => 'Local Passerby',
                        'role' => 'partner',
                        'text' => 'No problem at all! Walk straight past the clock tower and take the second turning on your left.',
                        'translation' => 'Sama sekali tidak apa-apa! Jalan lurus melewati menara jam dan ambil belokan kedua di sebelah kiri Anda.',
                        'audio_hint' => 'Perhatikan kata arah: past the clock tower, second turning on your left.',
                    ],
                    [
                        'speaker' => 'You',
                        'role' => 'user',
                        'text' => 'Is it far from here? Should I take a taxi instead?',
                        'translation' => 'Apakah jauh dari sini? Sebaiknya saya naik taksi saja?',
                        'audio_hint' => 'Intonasi bertanya naik di akhir.',
                    ],
                    [
                        'speaker' => 'Local Passerby',
                        'role' => 'partner',
                        'text' => 'Not at all, it\'s only a five-minute walk. You cannot miss the big red sign.',
                        'translation' => 'Sama sekali tidak, hanya sekitar lima menit jalan kaki. Anda tidak akan terlewat plang merah besarnya.',
                        'audio_hint' => 'Frasa "You cannot miss it" berarti sangat mudah ditemukan.',
                    ],
                    [
                        'speaker' => 'You',
                        'role' => 'user',
                        'text' => 'That\'s brilliant! Thank you so much for your kind help!',
                        'translation' => 'Luar biasa! Terima kasih banyak atas bantuan baik Anda!',
                        'audio_hint' => 'Ekspresikan rasa terima kasih dengan hangat.',
                    ],
                ],
            ],
            [
                'title' => 'Wawancara Kerja: Memperkenalkan Diri & Pengalaman',
                'level' => 'advanced',
                'scenario_tag' => 'Karir & Interview',
                'description' => 'Menjawab pertanyaan klasik pewawancara kerja internasional: "Tell me about yourself".',
                'dialogue_script' => [
                    [
                        'speaker' => 'Interviewer',
                        'role' => 'partner',
                        'text' => 'Welcome to our office! To kick things off, could you tell me a little bit about yourself?',
                        'translation' => 'Selamat datang di kantor kami! Sebagai permulaan, bisakah Anda menceritakan sedikit tentang diri Anda?',
                        'audio_hint' => 'Pertanyaan pembuka standar wawancara kerja profesional.',
                    ],
                    [
                        'speaker' => 'You',
                        'role' => 'user',
                        'text' => 'Thank you for this opportunity. I have over four years of experience in product design and user research.',
                        'translation' => 'Terima kasih atas kesempatan ini. Saya memiliki pengalaman lebih dari 4 tahun dalam desain produk dan riset pengguna.',
                        'audio_hint' => 'Ucapkan dengan percaya diri dan tempo stabil.',
                    ],
                    [
                        'speaker' => 'Interviewer',
                        'role' => 'partner',
                        'text' => 'Impressive! What do you consider your greatest strength when facing tight deadlines?',
                        'translation' => 'Mengesankan! Apa yang Anda anggap sebagai kekuatan terbesar saat menghadapi tenggat waktu yang ketat?',
                        'audio_hint' => 'Pertanyaan evaluasi ketahanan kerja.',
                    ],
                    [
                        'speaker' => 'You',
                        'role' => 'user',
                        'text' => 'My biggest strength is clear communication and prioritizing tasks that deliver the highest business value.',
                        'translation' => 'Kekuatan terbesar saya adalah komunikasi yang jelas dan memprioritaskan tugas-tugas yang memberikan nilai bisnis tertinggi.',
                        'audio_hint' => 'Jawab dengan terstruktur.',
                    ],
                    [
                        'speaker' => 'Interviewer',
                        'role' => 'partner',
                        'text' => 'That aligns perfectly with our team culture. Let us dive into your portfolio.',
                        'translation' => 'Itu sangat selaras dengan budaya tim kami. Mari kita bedah portofolio Anda.',
                        'audio_hint' => 'Respon positif pewawancara.',
                    ],
                ],
            ],
            [
                'title' => 'Check-in Kamar Hotel & Fasilitas',
                'level' => 'daily',
                'scenario_tag' => 'Hotel & Liburan',
                'description' => 'Berkomunikasi dengan staf resepsionis hotel mengenai pesanan kamar, sarapan pagi, dan kunci kamar.',
                'dialogue_script' => [
                    [
                        'speaker' => 'Receptionist',
                        'role' => 'partner',
                        'text' => 'Good evening, welcome to The Grand Hotel! Are you checking in today?',
                        'translation' => 'Selamat malam, selamat datang di The Grand Hotel! Apakah Anda mau check-in hari ini?',
                        'audio_hint' => 'Sapaan ramah khas staf perhotelan internasional.',
                    ],
                    [
                        'speaker' => 'You',
                        'role' => 'user',
                        'text' => 'Good evening! Yes, I have a reservation under the name Maya Hartanto for three nights.',
                        'translation' => 'Selamat malam! Ya, saya punya reservasi atas nama Maya Hartanto untuk 3 malam.',
                        'audio_hint' => 'Sebutkan nama dan durasi menginap dengan jelas.',
                    ],
                    [
                        'speaker' => 'Receptionist',
                        'role' => 'partner',
                        'text' => 'Perfect, I found your booking! A deluxe queen room on the tenth floor. May I see your ID passport, please?',
                        'translation' => 'Bagus sekali, pemesanan Anda sudah ditemukan! Kamar deluxe queen di lantai 10. Boleh saya lihat paspor Anda?',
                        'audio_hint' => 'Permintaan identitas tamu.',
                    ],
                    [
                        'speaker' => 'You',
                        'role' => 'user',
                        'text' => 'Here is my passport. Could you please tell me what time breakfast is served?',
                        'translation' => 'Ini paspor saya. Bisakah Anda memberi tahu jam berapa sarapan pagi disajikan?',
                        'audio_hint' => 'Menanyakan jam sarapan.',
                    ],
                    [
                        'speaker' => 'Receptionist',
                        'role' => 'partner',
                        'text' => 'Complimentary breakfast is served from 6:30 to 10:00 AM on the second floor. Here are your keycards!',
                        'translation' => 'Sarapan gratis disajikan pukul 06.30 hingga 10.00 di lantai 2. Ini kartu kunci kamar Anda!',
                        'audio_hint' => 'Penjelasan fasilitas dan penyerahan kunci.',
                    ],
                    [
                        'speaker' => 'You',
                        'role' => 'user',
                        'text' => 'That sounds wonderful. Thank you very much for your great assistance!',
                        'translation' => 'Kedengarannya luar biasa. Terima kasih banyak atas bantuan Anda yang hebat!',
                        'audio_hint' => 'Ucapan terima kasih ramah.',
                    ],
                ],
            ],
        ];

        foreach ($conversations as $c) {
            Conversation::updateOrCreate(
                ['title' => $c['title']],
                $c
            );
        }
    }
}
